### ISSUE TITLE
Assumes the module has access to shell environment variables

### ISSUE THREAD

**Issue by jeffboyus** [nlf/precommit-hook#14]
Is there a way to enhance or modify this module so that it can be ran outside of the shell environment?  Running this module from GUI Git clients most likely results in an access error because the clients do not run in the shell process but rather their own; therefore, trying to get access to shell variables are assumed and not actually available to the process. Sorry in advance if my question is a bit newbish when it comes to the shell.

Here is some direction from one such GUI client (Tower):

Are Hook scripts supported in Tower?
Yes, hook scripts are respected by Tower. Please note: Do your hook scripts rely on the existence or on specific values of shell environment variables that are created/modified in your shell profile (like extending "PATH" by a non-standard-path (e.g. '~/bin') to run a script from there in the hook)?

If the answer is yes, then you need to make sure you're creating the required shell environment in the hook script itself (like modifying "PATH"), not in your shell profile, as the hook script is called from the Tower process environment which is not running in a shell environment (hence your shell profile is not loaded).

**Comment by keeganstreet** [comment]
Hi @nlf,

I have tried adding the following line: `export PATH=$PATH:/usr/local/bin` to the `pre-commit` hook file so that SourceTree has access to node, as suggested at https://answers.atlassian.com/questions/140339/sourcetree-hook-failing-because-paths-don-t-seem-to-be-set-correctly. But then when I try to commit I see the following error:

`
sed: 1: "s/
$//": unterminated substitute pattern
EXPECTED value GOT EOF
failed parsing /Users/kestreet/myproject/package.json.. exiting
`

Do you know why modifying the path file would cause precommit-hook to have problems parsing the package.json file?

Thanks,
Keegan

**Comment by keeganstreet** [comment]
I can answer my own question. If I edit the `pre-commit` file with my usual code editor "Sublime Text", the line ending is changed, which triggers this issue. If I edit the `pre-commit` file in vim, it works fine. Now I can use precommit-hook with SourceTree! :-)

**Comment by shawn-simon** [comment]
Still an issue ...

**Comment by nlf** [comment]
@shawn-simon i assume you mean the linebreak issue above? that was filed as #62. i'll have a fix soon
