### ISSUE TITLE
Support another linters?

### ISSUE THREAD

**Issue by inca** [nlf/precommit-hook#56]
Awesome tool, but currently it unconditionally copies default `.jshintrc` and other stuff. We use ESLint, so each time we `npm i` we also need to manually remove artifacts generated by precommit-hook.

**Comment by Trott** [comment]
@nlf  may have a whole lot more to say, but briefly: This module uses [git-validate](https://github.com/nlf/git-validate) which is what anyone can use to write their own generic git hook validator/linter/tester/whatever-er.

**Comment by inca** [comment]
I am only worried about `npm i` creating magic files which is certainly uncalled for.

**Comment by nlf** [comment]
The only "magic file" is the `.validate.json` which was only added as a way to avoid having to edit a user's `package.json` for them to provide defaults. I'm starting to have second thoughts about this though, and debating if just modifying the `package.json` is the way to go.. Anyone have any thoughts?

**Comment by DadaMonad** [comment]
I am also using eslint instead of jslint. It would be nice if *precommit-hook* could provide a generic solution for executing  **stuff** before commiting. This is exactly what I need. 

I agree with @Trott. The creation of `.jshintrc` and `.jshintignore` was unexpected (yeah I didn't read the whole documentation). The reason for this is mainly because the repository description does not really focus on jslint being the primary application of this library.
In my opinion: If your users use a linter (e.g. jslint) they can configure it by themselves - you don't need to provide default configurations for them. Some of them may not even want a `.jshintignore` file ;)

As for the `.validate.json`: It would be nice if it is not created when I already have it in my package.json.

**Comment by inca** [comment]
I ended up using [pre-commit](https://www.npmjs.com/package/pre-commit).

**Comment by nlf** [comment]
fyi this is now more easily doable by installing git-validate directly instead of this project
