### ISSUE TITLE
Option to skip installation of jshint files

### ISSUE THREAD

**Issue by jhurliman** [nlf/precommit-hook#65]
We're using eslint for linting and the jshint config files are adding a bit of confusion since it can automatically enable linting by both jshint and eslint in some editor setups. Is there a way to use precommit-hook without adding any jshint files to our repo?

**Comment by nlf** [comment]
Use [git-validate](https://github.com/nlf/git-validate) directly, or fork this repo, swap out the jshint config files for eslint config files, and update the install script and package.json and publish it under a different name if you want to provide configuration when installing.

**Comment by jhurliman** [comment]
Done: https://www.npmjs.com/package/precommit-hook-eslint

**Comment by Trott** [comment]
@nlf If you haven't done it already, I'd recommend coming up with a keyword for people to put in `package.json` so that there's an easy way to find all the precommit-hook implementations on npm the way (for example) all browserify transforms should have the browserify-transform keyword and can therefore be found at https://www.npmjs.com/browse/keyword/browserify-transform

**Comment by nlf** [comment]
that's a good idea
