### ISSUE TITLE
unnecessary jshint dependency

### ISSUE THREAD

**Issue by noelmace** [nlf/precommit-hook#69]
I'm using eslint ... I don't see the need to have a jshint dependency in this project, since it add a bunch of configuration I don't need nor want.

**Comment by nlf** [comment]
jshint is the point of this module. if you don't want jshint, use git-validate directly or write your own module similar to this one that leverages git-validate

**Comment by cdaringe** [comment]
Hey @nlf!  Respectfully, is it the point?  I love your module here, use it frequently, and regularly don't use jshint with it.  Seemed like powerful language for a reasonable issue.  I'd  be a fan of pulling out the dep as well.  The configurability youve built in is part of what makes precommit-hook great!

**Comment by nlf** [comment]
it absolutely is the point of this specific module. if you look at the code for this module, it's essentially nothing more than some presets for git-validate. git-validate is where all the real work is done. that's why i said that if you want the features of this module, but you don't want jshint, just use git-validate directly. it doesn't install any dependencies at all.

**Comment by IanVS** [comment]
It might be worth updating the beginning of the README, then, because right now it says:

> It allows you to run any scripts defined in your package.json before a commit is made.

You could instead specify that it is for jshint, and suggest using `git-validate` for other tasks.

**Comment by borisdiakur** [comment]
This packege should be named precommit-hook-jshint consequently.

**Comment by Stupidism** [comment]
https://www.npmjs.com/package/precommit-hook-eslint

**Comment by smnbbrv** [comment]
@nlf if you have a package named precommit-hook, I believe, you should change something in your understanding of what should and what should not be in there. I understand your point, but there is one thing called "You become responsible forever, for what you have tamed.". You reserved a name, so, please, accept the consequence.

This issue really bothers people (and me; I also do not need any jshint in my project) and is easy to fix: just add another option on package.json to disable the .jshintrc and .jshintignore. Call it whatever "pre-commit-no-jshint": true and that is simply it! 

This will leave the default (legacy?) support for jshint and will not annoy others. After that you will never have the discussion again.

**Comment by nlf** [comment]
@smnbbrv as i've said more times than i can count, if you don't want the jshint files use [git-validate](https://github.com/nlf/git-validate) directly instead of this. literally all this module provides is a couple of default files for git-validate.

don't want the default files? just use git-validate. simple. i've even written that in this exact same issue's comment thread before. `precommit-hook-no-jshint` would be completely and utterly pointless because _it already exists_ as git-validate and i already thought i wouldn't have to have this conversation again.

i was _pretty sure_ this note wasn't too subtle:
![the readme in front of you](https://cldup.com/_KagkjUajC-3000x3000.png)

as to your comments, i understand completely what _i_ wanted in _my_ module seeing as _i_ wrote it for _me_. and yes, i am responsible for what i tame, which is exactly why i kept this module the way it was. there are no "consequences" to my reserving a module name. having a module named `backflipping-tortoise` doesn't mean i need to go to the pet store and start a miniature circus.
